//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIBER_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_del_Servicio
    {
        public int id_detalledeservicio { get; set; }
        public int id_venta { get; set; }
        public int id_servicio { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual Servicio Servicio { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
