//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIBER_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int id_empleados { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<int> id_direccion { get; set; }

        internal static object toList()
        {
            throw new NotImplementedException();
        }

        public string Telefono { get; set; }
        public int id_cargo { get; set; }
        public int id_sexo { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual Sexo Sexo { get; set; }
    }
}
