//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIBER_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Detalle_de_Compra = new HashSet<Detalle_de_Compra>();
        }
    
        public int id_productos { get; set; }
        public string Nombre_del_producto { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<System.DateTime> Fecha_de_vencimiento { get; set; }
        public Nullable<double> Precio_unitario { get; set; }
        public Nullable<int> id_proveedores { get; set; }
        public Nullable<int> Cantidad_existente { get; set; }
        public Nullable<int> Stock_maximo { get; set; }
        public Nullable<int> Stock_minimo { get; set; }
    
        public virtual Categoria_del_producto Categoria_del_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_de_Compra> Detalle_de_Compra { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
